# Generated by Django 6.0.2 on 2026-03-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Месяц (1–12)')),
                ('target', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='План (сом)')),
                ('note', models.CharField(blank=True, default='', max_length=300, verbose_name='Заметка')),
            ],
            options={
                'verbose_name': 'Плановая выручка',
                'verbose_name_plural': 'Плановая выручка',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
