# Generated by Django 6.0.2 on 2026-04-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, unique=True, verbose_name='Номер WhatsApp')),
                ('state', models.CharField(choices=[('start', 'Начало'), ('await_branch', 'Ожидает выбор филиала'), ('await_dates', 'Ожидает даты заезда/выезда'), ('await_guests', 'Ожидает количество гостей'), ('await_room', 'Ожидает тип номера'), ('await_name', 'Ожидает имя')], default='start', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Данные сессии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сессия WhatsApp',
                'verbose_name_plural': 'Сессии WhatsApp',
            },
        ),
    ]
