# Generated by Django 6.0.2 on 2026-04-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsession',
            name='lang',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='ru', max_length=5),
        ),
        migrations.AlterField(
            model_name='whatsappsession',
            name='state',
            field=models.CharField(choices=[('start', 'Начало'), ('await_lang', 'Ожидает язык'), ('await_branch', 'Ожидает выбор филиала'), ('await_dates', 'Ожидает даты заезда/выезда'), ('await_guests', 'Ожидает количество гостей'), ('await_room', 'Ожидает тип номера'), ('await_name', 'Ожидает имя')], default='start', max_length=20),
        ),
    ]
