# Generated by Django 6.0.2 on 2026-04-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa_bot', '0002_whatsappsession_lang_alter_whatsappsession_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppProcessedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=200, unique=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Обработанное событие WhatsApp',
                'verbose_name_plural': 'Обработанные события WhatsApp',
            },
        ),
    ]
