# Generated by Django 6.0.2 on 2026-04-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa_bot', '0003_whatsappprocessedevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappsession',
            name='state',
            field=models.CharField(choices=[('start', 'Начало'), ('await_lang', 'Ожидает язык'), ('await_branch', 'Ожидает выбор филиала'), ('await_dates', 'Ожидает даты заезда/выезда'), ('await_guests', 'Ожидает количество гостей'), ('await_private', 'Ожидает выбор приватности'), ('await_room', 'Ожидает тип номера'), ('await_bed', 'Ожидает подтверждение preview'), ('await_room_choice', 'Ожидает выбор конкретной комнаты'), ('await_name', 'Ожидает имя')], default='start', max_length=20),
        ),
    ]
