# Generated by Django 6.0.2 on 2026-03-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон / WhatsApp')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('checkin', models.DateField(verbose_name='Дата заезда')),
                ('checkout', models.DateField(verbose_name='Дата выезда')),
                ('guests', models.PositiveSmallIntegerField(default=1, verbose_name='Количество гостей')),
                ('room', models.CharField(blank=True, choices=[('Одноместный', 'Одноместный'), ('Двухместный', 'Двухместный'), ('Семейный', 'Семейный'), ('Дормитори', 'Дормитори')], default='', max_length=20, verbose_name='Тип номера')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Пожелания')),
                ('country', models.CharField(max_length=100, verbose_name='Страна прибытия')),
                ('purpose', models.CharField(choices=[('tourism', 'Туризм'), ('business', 'Бизнес'), ('transit', 'Транзит'), ('study', 'Учёба'), ('family', 'Семья / родственники'), ('other', 'Другое')], max_length=20, verbose_name='Цель визита')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждён'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
    ]
