# Generated by Django 6.0.2 on 2026-04-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_source_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за ночь'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая сумма'),
        ),
    ]
