# Generated by Django 6.0.2 on 2026-04-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_price_per_night_booking_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.CharField(blank=True, choices=[('single', 'Одноместная'), ('dorm_2', 'Дорм 2-местный'), ('dorm_4', 'Дорм 4-местный'), ('dorm_6', 'Дорм 6-местный'), ('dorm_8', 'Дорм 8-местный'), ('double_together', 'Двухместная (вместе)'), ('double_separate', 'Двухместная (раздельная)')], default='', max_length=20, verbose_name='Тип номера'),
        ),
    ]
