# Generated by Django 6.0.2 on 2026-04-02 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_room'),
        ('rooms', '0004_alter_room_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('single', 'Одноместная'), ('dorm_2', 'Дорм 2-местный'), ('dorm_4', 'Дорм 4-местный'), ('dorm_6', 'Дорм 6-местный'), ('dorm_8', 'Дорм 8-местный'), ('double_together', 'Двухместная (вместе)'), ('double_separate', 'Двухместная (раздельная)')], max_length=20, verbose_name='Тип номера')),
                ('url', models.URLField(max_length=500, verbose_name='Ссылка на .ics (экспорт с агрегатора)')),
                ('source', models.CharField(choices=[('airbnb', 'Airbnb'), ('booking_com', 'Booking.com')], max_length=20, verbose_name='Платформа')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ical_links', to='rooms.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'iCal Календарь',
                'verbose_name_plural': 'iCal Календари',
                'unique_together': {('branch', 'room_type', 'source')},
            },
        ),
    ]
