# Generated by Django 6.0.2 on 2026-04-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_icallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.CharField(blank=True, choices=[('single', 'Одноместная'), ('double', 'Двухместная'), ('family', 'Семейная'), ('dormitory', 'Дормитори'), ('dorm_2', 'Дорм 2-местный'), ('dorm_4', 'Дорм 4-местный'), ('dorm_6', 'Дорм 6-местный'), ('dorm_8', 'Дорм 8-местный'), ('double_together', 'Двухместная (вместе)'), ('double_separate', 'Двухместная (раздельная)')], default='', max_length=20, verbose_name='Тип номера'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='source',
            field=models.CharField(choices=[('direct', 'Прямое (сайт)'), ('booking_com', 'Booking.com'), ('airbnb', 'Airbnb'), ('walk_in', 'Walk-in'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], default='direct', max_length=20, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='icallink',
            name='room_type',
            field=models.CharField(choices=[('single', 'Одноместная'), ('double', 'Двухместная'), ('family', 'Семейная'), ('dormitory', 'Дормитори'), ('dorm_2', 'Дорм 2-местный'), ('dorm_4', 'Дорм 4-местный'), ('dorm_6', 'Дорм 6-местный'), ('dorm_8', 'Дорм 8-местный'), ('double_together', 'Двухместная (вместе)'), ('double_separate', 'Двухместная (раздельная)')], max_length=20, verbose_name='Тип номера'),
        ),
    ]
