# Generated by Django 6.0.2 on 2026-04-24 07:23

import django.db.models.deletion
from django.db import migrations, models


ACTIVE_STATUSES = ("pending", "confirmed")
TAG_LEGACY_OVERLAP = "[legacy_bed_assigned]"
TAG_LEGACY_NO_ROOM = "[legacy_no_matching_room]"


def _mark(booking, tag: str) -> None:
    if tag in (booking.comment or ""):
        return
    booking.comment = ((booking.comment or "") + " " + tag).strip()
    booking.save(update_fields=["comment"])


def backfill_bookingbeds(apps, schema_editor):
    """
    Привязать исторические Booking (pending/confirmed) к шконкам.

    Алгоритм:
    1. Найти Room того же branch + room_type.
    2. Собрать их Bed, отфильтровать занятые на даты брони.
    3. Если свободных >= guests — взять первые guests.
    4. Иначе — взять guests штук из всех Bed (включая пересекающиеся) и
       пометить Booking.comment меткой [legacy_bed_assigned].
    5. Если Room нужного типа в филиале нет — пометить [legacy_no_matching_room],
       BookingBed не создавать.
    Идемпотентно: если у Booking уже есть BookingBed — пропускаем.
    """
    Room = apps.get_model("rooms", "Room")
    Bed = apps.get_model("rooms", "Bed")
    Booking = apps.get_model("bookings", "Booking")
    BookingBed = apps.get_model("bookings", "BookingBed")

    active = (
        Booking.objects
            .filter(status__in=ACTIVE_STATUSES)
            .order_by("checkin", "id")
    )

    for booking in active:
        if BookingBed.objects.filter(booking=booking).exists():
            continue

        if not booking.branch_id or not booking.room:
            _mark(booking, TAG_LEGACY_NO_ROOM)
            continue

        rooms = list(Room.objects.filter(
            branch_id=booking.branch_id,
            room_type=booking.room,
        ))
        if not rooms:
            _mark(booking, TAG_LEGACY_NO_ROOM)
            continue

        room_price = {r.id: r.price_per_night for r in rooms}
        beds = list(Bed.objects.filter(room_id__in=room_price.keys()))
        if not beds:
            _mark(booking, TAG_LEGACY_NO_ROOM)
            continue

        bed_ids = [b.id for b in beds]
        busy_ids = set(
            BookingBed.objects
                .filter(
                    bed_id__in=bed_ids,
                    checkin__lt=booking.checkout,
                    checkout__gt=booking.checkin,
                )
                .values_list("bed_id", flat=True)
        )
        free_beds = [b for b in beds if b.id not in busy_ids]

        guests = booking.guests or 1

        if len(free_beds) >= guests:
            picked = free_beds[:guests]
        else:
            fallback = free_beds + [b for b in beds if b.id in busy_ids]
            picked = fallback[:guests]
            _mark(booking, TAG_LEGACY_OVERLAP)

        for bed in picked:
            BookingBed.objects.create(
                booking=booking,
                bed=bed,
                checkin=booking.checkin,
                checkout=booking.checkout,
                price_per_night=room_price[bed.room_id],
            )


def remove_bookingbeds(apps, schema_editor):
    BookingBed = apps.get_model("bookings", "BookingBed")
    BookingBed.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_room_alter_booking_source_and_more'),
        ('rooms', '0006_bed'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField(verbose_name='Дата заезда')),
                ('checkout', models.DateField(verbose_name='Дата выезда')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ночь (snapshot)')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rooms.bed', verbose_name='Шконка')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='bookings.booking', verbose_name='Бронь')),
            ],
            options={
                'verbose_name': 'Шконка в брони',
                'verbose_name_plural': 'Шконки в бронях',
                'indexes': [models.Index(fields=['bed', 'checkin', 'checkout'], name='bookings_bo_bed_id_d9e5bb_idx'), models.Index(fields=['checkin', 'checkout'], name='bookings_bo_checkin_59e9be_idx')],
            },
        ),
        migrations.RunPython(backfill_bookingbeds, remove_bookingbeds),
    ]
