# Generated by Django 6.0.2 on 2026-04-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_bookingbed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_private_booking',
            field=models.BooleanField(default=False, help_text='Группа забрала комнату целиком — чужих не подсаживаем', verbose_name='Забронировано целой комнатой'),
        ),
    ]
