# Generated by Django 6.0.2 on 2026-03-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер комнаты')),
                ('room_type', models.CharField(choices=[('Одноместный', 'Одноместный'), ('Двухместный', 'Двухместный'), ('Семейный', 'Семейный'), ('Дормитори', 'Дормитори')], max_length=20, verbose_name='Тип')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='Вместимость')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за ночь (сом)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'ordering': ['number'],
            },
        ),
    ]
