# Generated by Django 6.0.2 on 2026-04-02 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_branch_room_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.branch', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveSmallIntegerField(verbose_name='Вместимость (чел.)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, help_text='Для дормов — цена за одну шконку/место', max_digits=8, verbose_name='Цена за ночь (сом)'),
        ),
    ]
