# Generated by Django 6.0.2 on 2026-04-02 13:23

import django.db.models.deletion
from django.db import migrations, models


def preserve_null_branch_rooms(apps, schema_editor):
    Room = apps.get_model('rooms', 'Room')
    Branch = apps.get_model('rooms', 'Branch')
    if Room.objects.filter(branch__isnull=True).exists():
        default_branch, _ = Branch.objects.get_or_create(name="Старый филиал (сохранено)")
        Room.objects.filter(branch__isnull=True).update(branch=default_branch)


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_branch_room_refactor'),
    ]

    operations = [
        migrations.RunPython(preserve_null_branch_rooms),
        migrations.AlterField(
            model_name='room',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.branch', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveSmallIntegerField(verbose_name='Вместимость (чел.)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, help_text='Для дормов — цена за одну шконку/место', max_digits=8, verbose_name='Цена за ночь (сом)'),
        ),
    ]
