# Generated by Django 6.0.2 on 2026-04-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_branch_alter_room_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Одноместная'), ('dorm_2', 'Дорм 2-местный (шконки)'), ('dorm_4', 'Дорм 4-местный (шконки)'), ('dorm_6', 'Дорм 6-местный (шконки)'), ('dorm_8', 'Дорм 8-местный (шконки)'), ('double_together', 'Двухместная (вместе)'), ('double_separate', 'Двухместная (раздельная)')], max_length=20, verbose_name='Тип'),
        ),
    ]
