# Generated by Django 6.0.2 on 2026-04-24 07:23

import django.db.models.deletion
from django.db import migrations, models


def generate_beds(apps, schema_editor):
    """Создать Bed под каждую Room.capacity — label '1'..'N'."""
    Room = apps.get_model("rooms", "Room")
    Bed = apps.get_model("rooms", "Bed")

    for room in Room.objects.all():
        for i in range(1, (room.capacity or 0) + 1):
            Bed.objects.get_or_create(room=room, label=str(i))


def remove_beds(apps, schema_editor):
    Bed = apps.get_model("rooms", "Bed")
    Bed.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Идентификатор шконки внутри комнаты: '1', '2', 'нижняя', 'у окна'", max_length=20, verbose_name='Метка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='rooms.room', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Шконка',
                'verbose_name_plural': 'Шконки',
                'ordering': ['room', 'label'],
                'unique_together': {('room', 'label')},
            },
        ),
        migrations.RunPython(generate_beds, remove_beds),
    ]
